POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "teste3@email.com",
  "password": "SenhaTeste123$"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNjg2MTQxNTIyfQ.zdzl4YSaoz-R0mdx4kGnVi1T3IqOGmUMmKhpG9jCoGE

### 
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "teste",
  "email": "teste@email.com",
  "password": "Password123$"
}

### 
PUT http://localhost:3000/user/2
Content-Type: application/json

{
  "name": "nometeste",
  "email": "teste@email.com",
  "password": "SenhaTeste123$"
}

### 
DELETE http://localhost:3000/user/2
